apiVersion: v1
kind: Secret
metadata:
  name: ethos-ai-secrets
  namespace: swbc-ethos-ai
type: Opaque
stringData:
  VITE_USER_POOL_ID: "us-east-1_gYh3rcIFz"
  VITE_USER_POOL_CLIENT_ID: "6mlu9llcomgp1iokfk3552tvs3"
  VITE_IDENTITY_POOL_ID: "us-east-1:c4d5c67a-30d9-49ac-bc80-542775e19d9d"
  VITE_GRAPHQL_ENDPOINT: "https://y7sc7o27czcp3pw6lyib6ma2we.appsync-api.us-east-1.amazonaws.com/graphql"
  VITE_GRAPHQL_API_ID: "u3e7wpkmkrevbkkho5rh6pqf6u"
  VITE_S3_BUCKET: "insightsphere-dev-exports-327052515912"
  VITE_CHATLOG_TABLE: "UnityAIAssistantLogs"
  VITE_FEEDBACK_TABLE: "userFeedback"
  VITE_EVAL_JOB_TABLE: "UnityAIAssistantEvalJob"
  VITE_SENTRY_DSN: ""